services:
  api:
    container_name: teste-tecnico-node
    build: .
    command: ["npm", "start"]
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:16.1
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
